// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: planet/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b55d081339b1f1e, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b55d081339b1f1e, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetTwitterCoinsRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Index    string `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetTwitterCoinsRequest) Reset()         { *m = QueryGetTwitterCoinsRequest{} }
func (m *QueryGetTwitterCoinsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetTwitterCoinsRequest) ProtoMessage()    {}
func (*QueryGetTwitterCoinsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b55d081339b1f1e, []int{2}
}
func (m *QueryGetTwitterCoinsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTwitterCoinsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTwitterCoinsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTwitterCoinsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTwitterCoinsRequest.Merge(m, src)
}
func (m *QueryGetTwitterCoinsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTwitterCoinsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTwitterCoinsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTwitterCoinsRequest proto.InternalMessageInfo

func (m *QueryGetTwitterCoinsRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryGetTwitterCoinsRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetTwitterCoinsResponse struct {
	TwitterCoins TwitterCoins `protobuf:"bytes,1,opt,name=twitterCoins,proto3" json:"twitterCoins"`
}

func (m *QueryGetTwitterCoinsResponse) Reset()         { *m = QueryGetTwitterCoinsResponse{} }
func (m *QueryGetTwitterCoinsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetTwitterCoinsResponse) ProtoMessage()    {}
func (*QueryGetTwitterCoinsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b55d081339b1f1e, []int{3}
}
func (m *QueryGetTwitterCoinsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTwitterCoinsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTwitterCoinsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTwitterCoinsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTwitterCoinsResponse.Merge(m, src)
}
func (m *QueryGetTwitterCoinsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTwitterCoinsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTwitterCoinsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTwitterCoinsResponse proto.InternalMessageInfo

func (m *QueryGetTwitterCoinsResponse) GetTwitterCoins() TwitterCoins {
	if m != nil {
		return m.TwitterCoins
	}
	return TwitterCoins{}
}

type QueryAllTwitterCoinsRequest struct {
	Username   string             `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTwitterCoinsRequest) Reset()         { *m = QueryAllTwitterCoinsRequest{} }
func (m *QueryAllTwitterCoinsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllTwitterCoinsRequest) ProtoMessage()    {}
func (*QueryAllTwitterCoinsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b55d081339b1f1e, []int{4}
}
func (m *QueryAllTwitterCoinsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTwitterCoinsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTwitterCoinsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTwitterCoinsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTwitterCoinsRequest.Merge(m, src)
}
func (m *QueryAllTwitterCoinsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTwitterCoinsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTwitterCoinsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTwitterCoinsRequest proto.InternalMessageInfo

func (m *QueryAllTwitterCoinsRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryAllTwitterCoinsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllTwitterCoinsResponse struct {
	TwitterCoins []TwitterCoins      `protobuf:"bytes,1,rep,name=twitterCoins,proto3" json:"twitterCoins"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTwitterCoinsResponse) Reset()         { *m = QueryAllTwitterCoinsResponse{} }
func (m *QueryAllTwitterCoinsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllTwitterCoinsResponse) ProtoMessage()    {}
func (*QueryAllTwitterCoinsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b55d081339b1f1e, []int{5}
}
func (m *QueryAllTwitterCoinsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTwitterCoinsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTwitterCoinsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTwitterCoinsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTwitterCoinsResponse.Merge(m, src)
}
func (m *QueryAllTwitterCoinsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTwitterCoinsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTwitterCoinsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTwitterCoinsResponse proto.InternalMessageInfo

func (m *QueryAllTwitterCoinsResponse) GetTwitterCoins() []TwitterCoins {
	if m != nil {
		return m.TwitterCoins
	}
	return nil
}

func (m *QueryAllTwitterCoinsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetDNSRegistryRequest struct {
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (m *QueryGetDNSRegistryRequest) Reset()         { *m = QueryGetDNSRegistryRequest{} }
func (m *QueryGetDNSRegistryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDNSRegistryRequest) ProtoMessage()    {}
func (*QueryGetDNSRegistryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b55d081339b1f1e, []int{6}
}
func (m *QueryGetDNSRegistryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDNSRegistryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDNSRegistryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDNSRegistryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDNSRegistryRequest.Merge(m, src)
}
func (m *QueryGetDNSRegistryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDNSRegistryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDNSRegistryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDNSRegistryRequest proto.InternalMessageInfo

func (m *QueryGetDNSRegistryRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type QueryGetDNSRegistryResponse struct {
	DNSRegistry DNSRegistry `protobuf:"bytes,1,opt,name=dNSRegistry,proto3" json:"dNSRegistry"`
}

func (m *QueryGetDNSRegistryResponse) Reset()         { *m = QueryGetDNSRegistryResponse{} }
func (m *QueryGetDNSRegistryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDNSRegistryResponse) ProtoMessage()    {}
func (*QueryGetDNSRegistryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b55d081339b1f1e, []int{7}
}
func (m *QueryGetDNSRegistryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDNSRegistryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDNSRegistryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDNSRegistryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDNSRegistryResponse.Merge(m, src)
}
func (m *QueryGetDNSRegistryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDNSRegistryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDNSRegistryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDNSRegistryResponse proto.InternalMessageInfo

func (m *QueryGetDNSRegistryResponse) GetDNSRegistry() DNSRegistry {
	if m != nil {
		return m.DNSRegistry
	}
	return DNSRegistry{}
}

type QueryAllDNSRegistryRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDNSRegistryRequest) Reset()         { *m = QueryAllDNSRegistryRequest{} }
func (m *QueryAllDNSRegistryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllDNSRegistryRequest) ProtoMessage()    {}
func (*QueryAllDNSRegistryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b55d081339b1f1e, []int{8}
}
func (m *QueryAllDNSRegistryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDNSRegistryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDNSRegistryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDNSRegistryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDNSRegistryRequest.Merge(m, src)
}
func (m *QueryAllDNSRegistryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDNSRegistryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDNSRegistryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDNSRegistryRequest proto.InternalMessageInfo

func (m *QueryAllDNSRegistryRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllDNSRegistryResponse struct {
	DNSRegistry []DNSRegistry       `protobuf:"bytes,1,rep,name=dNSRegistry,proto3" json:"dNSRegistry"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDNSRegistryResponse) Reset()         { *m = QueryAllDNSRegistryResponse{} }
func (m *QueryAllDNSRegistryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllDNSRegistryResponse) ProtoMessage()    {}
func (*QueryAllDNSRegistryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b55d081339b1f1e, []int{9}
}
func (m *QueryAllDNSRegistryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDNSRegistryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDNSRegistryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDNSRegistryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDNSRegistryResponse.Merge(m, src)
}
func (m *QueryAllDNSRegistryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDNSRegistryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDNSRegistryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDNSRegistryResponse proto.InternalMessageInfo

func (m *QueryAllDNSRegistryResponse) GetDNSRegistry() []DNSRegistry {
	if m != nil {
		return m.DNSRegistry
	}
	return nil
}

func (m *QueryAllDNSRegistryResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "mercestoken.planet.planet.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "mercestoken.planet.planet.QueryParamsResponse")
	proto.RegisterType((*QueryGetTwitterCoinsRequest)(nil), "mercestoken.planet.planet.QueryGetTwitterCoinsRequest")
	proto.RegisterType((*QueryGetTwitterCoinsResponse)(nil), "mercestoken.planet.planet.QueryGetTwitterCoinsResponse")
	proto.RegisterType((*QueryAllTwitterCoinsRequest)(nil), "mercestoken.planet.planet.QueryAllTwitterCoinsRequest")
	proto.RegisterType((*QueryAllTwitterCoinsResponse)(nil), "mercestoken.planet.planet.QueryAllTwitterCoinsResponse")
	proto.RegisterType((*QueryGetDNSRegistryRequest)(nil), "mercestoken.planet.planet.QueryGetDNSRegistryRequest")
	proto.RegisterType((*QueryGetDNSRegistryResponse)(nil), "mercestoken.planet.planet.QueryGetDNSRegistryResponse")
	proto.RegisterType((*QueryAllDNSRegistryRequest)(nil), "mercestoken.planet.planet.QueryAllDNSRegistryRequest")
	proto.RegisterType((*QueryAllDNSRegistryResponse)(nil), "mercestoken.planet.planet.QueryAllDNSRegistryResponse")
}

func init() { proto.RegisterFile("planet/query.proto", fileDescriptor_2b55d081339b1f1e) }

var fileDescriptor_2b55d081339b1f1e = []byte{
	// 677 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x4f, 0x4f, 0x13, 0x4f,
	0x18, 0xc7, 0x3b, 0xf0, 0xa3, 0xf9, 0x39, 0x25, 0x9a, 0x0c, 0xc4, 0xc0, 0x4a, 0x56, 0x59, 0x13,
	0xfe, 0x45, 0x77, 0xa0, 0x0a, 0x7a, 0x33, 0xa0, 0x81, 0x93, 0x08, 0x95, 0x78, 0xf0, 0x42, 0xa6,
	0xed, 0x64, 0xdd, 0xb8, 0xbb, 0xb3, 0xec, 0x4c, 0x15, 0x42, 0x38, 0xe8, 0x2b, 0x30, 0xfa, 0x46,
	0x3c, 0x18, 0x12, 0x7d, 0x05, 0x1c, 0x49, 0xbc, 0x78, 0x32, 0x06, 0x7c, 0x17, 0x5e, 0xcc, 0xce,
	0x4c, 0x61, 0x36, 0x2c, 0xed, 0x16, 0x3c, 0xb5, 0x3b, 0x33, 0xcf, 0xf7, 0xf9, 0x7c, 0x9f, 0x67,
	0xf6, 0x69, 0x21, 0x8a, 0x03, 0x12, 0x51, 0x81, 0xb7, 0x5a, 0x34, 0xd9, 0x71, 0xe3, 0x84, 0x09,
	0x86, 0x46, 0x43, 0x9a, 0x34, 0x28, 0x17, 0xec, 0x35, 0x8d, 0x5c, 0xb5, 0xaf, 0x3f, 0xac, 0x61,
	0x8f, 0x79, 0x4c, 0x9e, 0xc2, 0xe9, 0x37, 0x15, 0x60, 0x8d, 0x79, 0x8c, 0x79, 0x01, 0xc5, 0x24,
	0xf6, 0x31, 0x89, 0x22, 0x26, 0x88, 0xf0, 0x59, 0xc4, 0xf5, 0xee, 0x4c, 0x83, 0xf1, 0x90, 0x71,
	0x5c, 0x27, 0x9c, 0xaa, 0x3c, 0xf8, 0xcd, 0x5c, 0x9d, 0x0a, 0x32, 0x87, 0x63, 0xe2, 0xf9, 0x91,
	0x3c, 0xac, 0xcf, 0x0e, 0x69, 0x9c, 0x98, 0x24, 0x24, 0x6c, 0x0b, 0x58, 0x7a, 0x51, 0xbc, 0xf5,
	0x85, 0xa0, 0xc9, 0x66, 0x83, 0xf9, 0x27, 0xe2, 0xa3, 0x7a, 0xaf, 0x19, 0xf1, 0xcd, 0x84, 0x7a,
	0x3e, 0x17, 0x6d, 0x1b, 0xce, 0x30, 0x44, 0xeb, 0x69, 0xb6, 0x35, 0xa9, 0x55, 0xa3, 0x5b, 0x2d,
	0xca, 0x85, 0xf3, 0x02, 0x0e, 0x65, 0x56, 0x79, 0xcc, 0x22, 0x4e, 0xd1, 0x23, 0x58, 0x56, 0x39,
	0x47, 0xc0, 0x2d, 0x30, 0x55, 0xa9, 0x8e, 0xbb, 0xe7, 0x16, 0xc1, 0x55, 0xa1, 0x4b, 0xff, 0x1d,
	0xfc, 0xbc, 0x59, 0xaa, 0xe9, 0x30, 0xe7, 0x19, 0xbc, 0x21, 0x75, 0x57, 0xa8, 0xd8, 0x50, 0x9c,
	0x8f, 0x53, 0x4c, 0x9d, 0x16, 0x59, 0xf0, 0xff, 0x16, 0xa7, 0x49, 0x44, 0x42, 0x2a, 0x33, 0x5c,
	0xa9, 0x9d, 0x3c, 0xa3, 0x61, 0x38, 0xe0, 0x47, 0x4d, 0xba, 0x3d, 0xd2, 0x27, 0x37, 0xd4, 0x83,
	0xb3, 0x05, 0xc7, 0xf2, 0x05, 0x35, 0xf1, 0x3a, 0x1c, 0x14, 0xc6, 0xba, 0xe6, 0x9e, 0xec, 0xc0,
	0x6d, 0xca, 0x68, 0xfa, 0x8c, 0x84, 0xf3, 0x0e, 0x68, 0x13, 0x8b, 0x41, 0xd0, 0xab, 0x89, 0x65,
	0x08, 0x4f, 0xbb, 0x29, 0x9d, 0x54, 0xaa, 0x13, 0xae, 0x6a, 0xbd, 0x9b, 0xb6, 0xde, 0x55, 0x57,
	0x4c, 0xb7, 0xde, 0x5d, 0x23, 0x1e, 0xd5, 0xba, 0x35, 0x23, 0xd2, 0xf9, 0x06, 0xb4, 0xef, 0x33,
	0x0c, 0xe7, 0xfa, 0xee, 0xbf, 0xa4, 0x6f, 0xb4, 0x92, 0xc3, 0x3e, 0xd9, 0x95, 0x5d, 0xf1, 0x64,
	0xe0, 0xef, 0x43, 0xab, 0xdd, 0xb3, 0x27, 0xab, 0xcf, 0x6b, 0xfa, 0x3e, 0xb6, 0xcb, 0x77, 0x1d,
	0x96, 0x9b, 0x2c, 0x24, 0x7e, 0xa4, 0x8b, 0xa7, 0x9f, 0x9c, 0xf0, 0xf4, 0xea, 0x64, 0xa2, 0xb4,
	0xe1, 0x55, 0x58, 0x69, 0x9e, 0x2e, 0xeb, 0x3e, 0x4f, 0x74, 0xf0, 0x6b, 0x88, 0x68, 0xbb, 0xa6,
	0x80, 0xd3, 0xd4, 0x90, 0x8b, 0x41, 0x90, 0x03, 0x99, 0xed, 0x23, 0xb8, 0x70, 0x1f, 0xf7, 0x8d,
	0xbb, 0x54, 0xc8, 0x55, 0xff, 0xa5, 0x5c, 0xfd, 0xb3, 0x1e, 0x56, 0xff, 0x94, 0xe1, 0x80, 0x04,
	0x47, 0x1f, 0x01, 0x2c, 0xab, 0x77, 0x1d, 0xdd, 0xed, 0x00, 0x76, 0x76, 0xc8, 0x58, 0x6e, 0xd1,
	0xe3, 0x2a, 0xbf, 0x33, 0xfd, 0xfe, 0xfb, 0xef, 0x4f, 0x7d, 0xb7, 0xd1, 0x38, 0x7e, 0x2a, 0xe3,
	0x36, 0xd2, 0x38, 0xdc, 0x9e, 0x85, 0xe6, 0x48, 0x44, 0x5f, 0x01, 0x1c, 0x34, 0x2f, 0x34, 0x5a,
	0xe8, 0x96, 0x2b, 0x7f, 0x22, 0x59, 0x0f, 0x7a, 0x8e, 0xd3, 0xb0, 0x0f, 0x25, 0x6c, 0x15, 0xcd,
	0x76, 0x80, 0xcd, 0x8c, 0x6a, 0xbc, 0x2b, 0x27, 0xda, 0x1e, 0xfa, 0x02, 0xe0, 0x35, 0x53, 0x72,
	0x31, 0x08, 0xba, 0xe3, 0xe7, 0xcf, 0xa2, 0xee, 0xf8, 0xe7, 0xcc, 0x0f, 0x67, 0x56, 0xe2, 0xcf,
	0xa0, 0xa9, 0xa2, 0xf8, 0x68, 0x1f, 0xc0, 0x8a, 0x71, 0xfb, 0xd0, 0x7c, 0x81, 0xca, 0x9d, 0x7d,
	0xb3, 0xac, 0x85, 0x5e, 0xc3, 0x7a, 0xa8, 0xb7, 0xf9, 0xf3, 0x87, 0x77, 0xd5, 0x5c, 0xd9, 0x43,
	0x9f, 0x01, 0xbc, 0x6a, 0x28, 0xa6, 0xe5, 0x9e, 0x2f, 0x50, 0xb6, 0x8b, 0xb0, 0xe7, 0xbf, 0xe5,
	0x0e, 0x96, 0xec, 0xd3, 0x68, 0xb2, 0x20, 0xfb, 0xd2, 0xf2, 0xc1, 0x91, 0x0d, 0x0e, 0x8f, 0x6c,
	0xf0, 0xeb, 0xc8, 0x06, 0x1f, 0x8e, 0xed, 0xd2, 0xe1, 0xb1, 0x5d, 0xfa, 0x71, 0x6c, 0x97, 0x5e,
	0xde, 0xf1, 0x7c, 0xf1, 0xaa, 0x55, 0x77, 0x1b, 0x2c, 0xcc, 0x13, 0xdb, 0x3e, 0xe9, 0xdd, 0x4e,
	0x4c, 0x79, 0xbd, 0x2c, 0xff, 0x03, 0xdc, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x81, 0xe0,
	0x08, 0xe0, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a TwitterCoins by index.
	TwitterCoins(ctx context.Context, in *QueryGetTwitterCoinsRequest, opts ...grpc.CallOption) (*QueryGetTwitterCoinsResponse, error)
	// Queries a list of TwitterCoins items.
	TwitterCoinsAll(ctx context.Context, in *QueryAllTwitterCoinsRequest, opts ...grpc.CallOption) (*QueryAllTwitterCoinsResponse, error)
	// Queries a DNSRegistry by index.
	DNSRegistry(ctx context.Context, in *QueryGetDNSRegistryRequest, opts ...grpc.CallOption) (*QueryGetDNSRegistryResponse, error)
	// Queries a list of DNSRegistry items.
	DNSRegistryAll(ctx context.Context, in *QueryAllDNSRegistryRequest, opts ...grpc.CallOption) (*QueryAllDNSRegistryResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/mercestoken.planet.planet.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TwitterCoins(ctx context.Context, in *QueryGetTwitterCoinsRequest, opts ...grpc.CallOption) (*QueryGetTwitterCoinsResponse, error) {
	out := new(QueryGetTwitterCoinsResponse)
	err := c.cc.Invoke(ctx, "/mercestoken.planet.planet.Query/TwitterCoins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TwitterCoinsAll(ctx context.Context, in *QueryAllTwitterCoinsRequest, opts ...grpc.CallOption) (*QueryAllTwitterCoinsResponse, error) {
	out := new(QueryAllTwitterCoinsResponse)
	err := c.cc.Invoke(ctx, "/mercestoken.planet.planet.Query/TwitterCoinsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DNSRegistry(ctx context.Context, in *QueryGetDNSRegistryRequest, opts ...grpc.CallOption) (*QueryGetDNSRegistryResponse, error) {
	out := new(QueryGetDNSRegistryResponse)
	err := c.cc.Invoke(ctx, "/mercestoken.planet.planet.Query/DNSRegistry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DNSRegistryAll(ctx context.Context, in *QueryAllDNSRegistryRequest, opts ...grpc.CallOption) (*QueryAllDNSRegistryResponse, error) {
	out := new(QueryAllDNSRegistryResponse)
	err := c.cc.Invoke(ctx, "/mercestoken.planet.planet.Query/DNSRegistryAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a TwitterCoins by index.
	TwitterCoins(context.Context, *QueryGetTwitterCoinsRequest) (*QueryGetTwitterCoinsResponse, error)
	// Queries a list of TwitterCoins items.
	TwitterCoinsAll(context.Context, *QueryAllTwitterCoinsRequest) (*QueryAllTwitterCoinsResponse, error)
	// Queries a DNSRegistry by index.
	DNSRegistry(context.Context, *QueryGetDNSRegistryRequest) (*QueryGetDNSRegistryResponse, error)
	// Queries a list of DNSRegistry items.
	DNSRegistryAll(context.Context, *QueryAllDNSRegistryRequest) (*QueryAllDNSRegistryResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) TwitterCoins(ctx context.Context, req *QueryGetTwitterCoinsRequest) (*QueryGetTwitterCoinsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TwitterCoins not implemented")
}
func (*UnimplementedQueryServer) TwitterCoinsAll(ctx context.Context, req *QueryAllTwitterCoinsRequest) (*QueryAllTwitterCoinsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TwitterCoinsAll not implemented")
}
func (*UnimplementedQueryServer) DNSRegistry(ctx context.Context, req *QueryGetDNSRegistryRequest) (*QueryGetDNSRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DNSRegistry not implemented")
}
func (*UnimplementedQueryServer) DNSRegistryAll(ctx context.Context, req *QueryAllDNSRegistryRequest) (*QueryAllDNSRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DNSRegistryAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mercestoken.planet.planet.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TwitterCoins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTwitterCoinsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TwitterCoins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mercestoken.planet.planet.Query/TwitterCoins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TwitterCoins(ctx, req.(*QueryGetTwitterCoinsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TwitterCoinsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllTwitterCoinsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TwitterCoinsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mercestoken.planet.planet.Query/TwitterCoinsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TwitterCoinsAll(ctx, req.(*QueryAllTwitterCoinsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DNSRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDNSRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DNSRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mercestoken.planet.planet.Query/DNSRegistry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DNSRegistry(ctx, req.(*QueryGetDNSRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DNSRegistryAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDNSRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DNSRegistryAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mercestoken.planet.planet.Query/DNSRegistryAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DNSRegistryAll(ctx, req.(*QueryAllDNSRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mercestoken.planet.planet.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "TwitterCoins",
			Handler:    _Query_TwitterCoins_Handler,
		},
		{
			MethodName: "TwitterCoinsAll",
			Handler:    _Query_TwitterCoinsAll_Handler,
		},
		{
			MethodName: "DNSRegistry",
			Handler:    _Query_DNSRegistry_Handler,
		},
		{
			MethodName: "DNSRegistryAll",
			Handler:    _Query_DNSRegistryAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "planet/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetTwitterCoinsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTwitterCoinsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTwitterCoinsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTwitterCoinsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTwitterCoinsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTwitterCoinsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TwitterCoins.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllTwitterCoinsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTwitterCoinsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTwitterCoinsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllTwitterCoinsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTwitterCoinsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTwitterCoinsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.TwitterCoins) > 0 {
		for iNdEx := len(m.TwitterCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TwitterCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDNSRegistryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDNSRegistryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDNSRegistryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDNSRegistryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDNSRegistryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDNSRegistryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.DNSRegistry.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllDNSRegistryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDNSRegistryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDNSRegistryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDNSRegistryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDNSRegistryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDNSRegistryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.DNSRegistry) > 0 {
		for iNdEx := len(m.DNSRegistry) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DNSRegistry[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetTwitterCoinsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetTwitterCoinsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TwitterCoins.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllTwitterCoinsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllTwitterCoinsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TwitterCoins) > 0 {
		for _, e := range m.TwitterCoins {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDNSRegistryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDNSRegistryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DNSRegistry.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllDNSRegistryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDNSRegistryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DNSRegistry) > 0 {
		for _, e := range m.DNSRegistry {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTwitterCoinsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTwitterCoinsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTwitterCoinsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTwitterCoinsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTwitterCoinsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTwitterCoinsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwitterCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TwitterCoins.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTwitterCoinsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTwitterCoinsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTwitterCoinsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTwitterCoinsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTwitterCoinsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTwitterCoinsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwitterCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TwitterCoins = append(m.TwitterCoins, TwitterCoins{})
			if err := m.TwitterCoins[len(m.TwitterCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDNSRegistryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDNSRegistryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDNSRegistryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDNSRegistryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDNSRegistryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDNSRegistryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DNSRegistry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DNSRegistry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDNSRegistryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDNSRegistryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDNSRegistryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDNSRegistryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDNSRegistryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDNSRegistryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DNSRegistry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DNSRegistry = append(m.DNSRegistry, DNSRegistry{})
			if err := m.DNSRegistry[len(m.DNSRegistry)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
