// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: planet/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgTransferFromTwitterToWalletByMerces struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Address  string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Denom    string `protobuf:"bytes,4,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount   int64  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgTransferFromTwitterToWalletByMerces) Reset() {
	*m = MsgTransferFromTwitterToWalletByMerces{}
}
func (m *MsgTransferFromTwitterToWalletByMerces) String() string { return proto.CompactTextString(m) }
func (*MsgTransferFromTwitterToWalletByMerces) ProtoMessage()    {}
func (*MsgTransferFromTwitterToWalletByMerces) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3460ff237fc793, []int{0}
}
func (m *MsgTransferFromTwitterToWalletByMerces) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferFromTwitterToWalletByMerces) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferFromTwitterToWalletByMerces.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferFromTwitterToWalletByMerces) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferFromTwitterToWalletByMerces.Merge(m, src)
}
func (m *MsgTransferFromTwitterToWalletByMerces) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferFromTwitterToWalletByMerces) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferFromTwitterToWalletByMerces.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferFromTwitterToWalletByMerces proto.InternalMessageInfo

func (m *MsgTransferFromTwitterToWalletByMerces) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgTransferFromTwitterToWalletByMerces) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MsgTransferFromTwitterToWalletByMerces) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgTransferFromTwitterToWalletByMerces) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MsgTransferFromTwitterToWalletByMerces) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type MsgTransferFromTwitterToWalletByMercesResponse struct {
}

func (m *MsgTransferFromTwitterToWalletByMercesResponse) Reset() {
	*m = MsgTransferFromTwitterToWalletByMercesResponse{}
}
func (m *MsgTransferFromTwitterToWalletByMercesResponse) String() string {
	return proto.CompactTextString(m)
}
func (*MsgTransferFromTwitterToWalletByMercesResponse) ProtoMessage() {}
func (*MsgTransferFromTwitterToWalletByMercesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3460ff237fc793, []int{1}
}
func (m *MsgTransferFromTwitterToWalletByMercesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferFromTwitterToWalletByMercesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferFromTwitterToWalletByMercesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferFromTwitterToWalletByMercesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferFromTwitterToWalletByMercesResponse.Merge(m, src)
}
func (m *MsgTransferFromTwitterToWalletByMercesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferFromTwitterToWalletByMercesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferFromTwitterToWalletByMercesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferFromTwitterToWalletByMercesResponse proto.InternalMessageInfo

type MsgTransferFromTwitterToTwitterByMerces struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	FromUsername string `protobuf:"bytes,2,opt,name=fromUsername,proto3" json:"fromUsername,omitempty"`
	ToUsername   string `protobuf:"bytes,3,opt,name=toUsername,proto3" json:"toUsername,omitempty"`
	Denom        string `protobuf:"bytes,4,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount       int64  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgTransferFromTwitterToTwitterByMerces) Reset() {
	*m = MsgTransferFromTwitterToTwitterByMerces{}
}
func (m *MsgTransferFromTwitterToTwitterByMerces) String() string { return proto.CompactTextString(m) }
func (*MsgTransferFromTwitterToTwitterByMerces) ProtoMessage()    {}
func (*MsgTransferFromTwitterToTwitterByMerces) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3460ff237fc793, []int{2}
}
func (m *MsgTransferFromTwitterToTwitterByMerces) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferFromTwitterToTwitterByMerces) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferFromTwitterToTwitterByMerces.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferFromTwitterToTwitterByMerces) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferFromTwitterToTwitterByMerces.Merge(m, src)
}
func (m *MsgTransferFromTwitterToTwitterByMerces) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferFromTwitterToTwitterByMerces) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferFromTwitterToTwitterByMerces.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferFromTwitterToTwitterByMerces proto.InternalMessageInfo

func (m *MsgTransferFromTwitterToTwitterByMerces) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgTransferFromTwitterToTwitterByMerces) GetFromUsername() string {
	if m != nil {
		return m.FromUsername
	}
	return ""
}

func (m *MsgTransferFromTwitterToTwitterByMerces) GetToUsername() string {
	if m != nil {
		return m.ToUsername
	}
	return ""
}

func (m *MsgTransferFromTwitterToTwitterByMerces) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MsgTransferFromTwitterToTwitterByMerces) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type MsgTransferFromTwitterToTwitterByMercesResponse struct {
}

func (m *MsgTransferFromTwitterToTwitterByMercesResponse) Reset() {
	*m = MsgTransferFromTwitterToTwitterByMercesResponse{}
}
func (m *MsgTransferFromTwitterToTwitterByMercesResponse) String() string {
	return proto.CompactTextString(m)
}
func (*MsgTransferFromTwitterToTwitterByMercesResponse) ProtoMessage() {}
func (*MsgTransferFromTwitterToTwitterByMercesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3460ff237fc793, []int{3}
}
func (m *MsgTransferFromTwitterToTwitterByMercesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferFromTwitterToTwitterByMercesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferFromTwitterToTwitterByMercesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferFromTwitterToTwitterByMercesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferFromTwitterToTwitterByMercesResponse.Merge(m, src)
}
func (m *MsgTransferFromTwitterToTwitterByMercesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferFromTwitterToTwitterByMercesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferFromTwitterToTwitterByMercesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferFromTwitterToTwitterByMercesResponse proto.InternalMessageInfo

type MsgTransferFromWalletToTwitter struct {
	Creator  string     `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Username string     `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Coin     types.Coin `protobuf:"bytes,3,opt,name=coin,proto3" json:"coin"`
}

func (m *MsgTransferFromWalletToTwitter) Reset()         { *m = MsgTransferFromWalletToTwitter{} }
func (m *MsgTransferFromWalletToTwitter) String() string { return proto.CompactTextString(m) }
func (*MsgTransferFromWalletToTwitter) ProtoMessage()    {}
func (*MsgTransferFromWalletToTwitter) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3460ff237fc793, []int{4}
}
func (m *MsgTransferFromWalletToTwitter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferFromWalletToTwitter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferFromWalletToTwitter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferFromWalletToTwitter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferFromWalletToTwitter.Merge(m, src)
}
func (m *MsgTransferFromWalletToTwitter) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferFromWalletToTwitter) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferFromWalletToTwitter.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferFromWalletToTwitter proto.InternalMessageInfo

func (m *MsgTransferFromWalletToTwitter) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgTransferFromWalletToTwitter) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MsgTransferFromWalletToTwitter) GetCoin() types.Coin {
	if m != nil {
		return m.Coin
	}
	return types.Coin{}
}

type MsgTransferFromWalletToTwitterResponse struct {
}

func (m *MsgTransferFromWalletToTwitterResponse) Reset() {
	*m = MsgTransferFromWalletToTwitterResponse{}
}
func (m *MsgTransferFromWalletToTwitterResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTransferFromWalletToTwitterResponse) ProtoMessage()    {}
func (*MsgTransferFromWalletToTwitterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a3460ff237fc793, []int{5}
}
func (m *MsgTransferFromWalletToTwitterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferFromWalletToTwitterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferFromWalletToTwitterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferFromWalletToTwitterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferFromWalletToTwitterResponse.Merge(m, src)
}
func (m *MsgTransferFromWalletToTwitterResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferFromWalletToTwitterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferFromWalletToTwitterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferFromWalletToTwitterResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgTransferFromTwitterToWalletByMerces)(nil), "mercestoken.planet.planet.MsgTransferFromTwitterToWalletByMerces")
	proto.RegisterType((*MsgTransferFromTwitterToWalletByMercesResponse)(nil), "mercestoken.planet.planet.MsgTransferFromTwitterToWalletByMercesResponse")
	proto.RegisterType((*MsgTransferFromTwitterToTwitterByMerces)(nil), "mercestoken.planet.planet.MsgTransferFromTwitterToTwitterByMerces")
	proto.RegisterType((*MsgTransferFromTwitterToTwitterByMercesResponse)(nil), "mercestoken.planet.planet.MsgTransferFromTwitterToTwitterByMercesResponse")
	proto.RegisterType((*MsgTransferFromWalletToTwitter)(nil), "mercestoken.planet.planet.MsgTransferFromWalletToTwitter")
	proto.RegisterType((*MsgTransferFromWalletToTwitterResponse)(nil), "mercestoken.planet.planet.MsgTransferFromWalletToTwitterResponse")
}

func init() { proto.RegisterFile("planet/tx.proto", fileDescriptor_8a3460ff237fc793) }

var fileDescriptor_8a3460ff237fc793 = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xce, 0x98, 0xb4, 0xea, 0x53, 0x10, 0x96, 0x22, 0xdb, 0x15, 0xc6, 0xb2, 0x8a, 0xe6, 0x20,
	0xb3, 0xa6, 0x3d, 0x79, 0x6c, 0x84, 0x82, 0x42, 0x2e, 0x21, 0x22, 0x78, 0x9b, 0x6c, 0x5e, 0xd7,
	0x60, 0x76, 0x5e, 0x98, 0x99, 0x68, 0xfb, 0x1b, 0xbc, 0x88, 0x57, 0xef, 0xfe, 0x01, 0xd1, 0xdf,
	0xd0, 0x63, 0x8f, 0x9e, 0x44, 0x92, 0x3f, 0x22, 0xbb, 0xb3, 0xbb, 0xd8, 0x95, 0xca, 0x36, 0x39,
	0xe5, 0x7d, 0x6f, 0xe6, 0x7b, 0xef, 0xfb, 0xb2, 0x1f, 0x03, 0x77, 0xe6, 0x33, 0xa9, 0xd0, 0x46,
	0xf6, 0x44, 0xcc, 0x35, 0x59, 0xf2, 0x76, 0x53, 0xd4, 0x31, 0x1a, 0x4b, 0xef, 0x50, 0x09, 0x77,
	0x58, 0xfc, 0x04, 0x3c, 0x26, 0x93, 0x92, 0x89, 0xc6, 0xd2, 0x60, 0xf4, 0xbe, 0x37, 0x46, 0x2b,
	0x7b, 0x51, 0x4c, 0x53, 0xe5, 0xa8, 0xc1, 0x4e, 0x42, 0x09, 0xe5, 0x65, 0x94, 0x55, 0xae, 0x1b,
	0x7e, 0x65, 0xf0, 0x68, 0x60, 0x92, 0x91, 0x96, 0xca, 0x1c, 0xa3, 0x3e, 0xd2, 0x94, 0x8e, 0x3e,
	0x4c, 0xad, 0x45, 0x3d, 0xa2, 0xd7, 0x72, 0x36, 0x43, 0xdb, 0x3f, 0x1d, 0xe4, 0x3b, 0x3d, 0x1f,
	0xae, 0xc7, 0x1a, 0xa5, 0x25, 0xed, 0xb3, 0x3d, 0xd6, 0xbd, 0x39, 0x2c, 0xa1, 0x17, 0xc0, 0x8d,
	0x85, 0x41, 0xad, 0x64, 0x8a, 0xfe, 0xb5, 0xfc, 0xa8, 0xc2, 0x19, 0x4b, 0x4e, 0x26, 0x1a, 0x8d,
	0xf1, 0xdb, 0x8e, 0x55, 0x40, 0x6f, 0x07, 0xb6, 0x26, 0xa8, 0x28, 0xf5, 0x3b, 0x79, 0xdf, 0x01,
	0xef, 0x2e, 0x6c, 0xcb, 0x94, 0x16, 0xca, 0xfa, 0x5b, 0x7b, 0xac, 0xdb, 0x1e, 0x16, 0x28, 0x7c,
	0x0a, 0xa2, 0x99, 0xce, 0x21, 0x9a, 0x39, 0x29, 0x83, 0xe1, 0x77, 0x06, 0x8f, 0x2f, 0xa3, 0x14,
	0x45, 0x03, 0x6f, 0x21, 0xdc, 0x3e, 0xd6, 0x94, 0xbe, 0xba, 0xe8, 0xef, 0x42, 0xcf, 0xe3, 0x00,
	0x96, 0xaa, 0x1b, 0xce, 0xe6, 0x5f, 0x9d, 0x2b, 0x3a, 0xed, 0x41, 0xd4, 0x50, 0x76, 0x65, 0xf5,
	0x23, 0x03, 0x5e, 0xe3, 0xb8, 0x3f, 0xa5, 0xa2, 0xac, 0xf9, 0xf5, 0x0e, 0xa0, 0x93, 0x45, 0x28,
	0xf7, 0x74, 0x6b, 0x7f, 0x57, 0xb8, 0x8c, 0x89, 0x2c, 0x63, 0xa2, 0xc8, 0x98, 0x78, 0x4e, 0x53,
	0xd5, 0xef, 0x9c, 0xfd, 0xba, 0xdf, 0x1a, 0xe6, 0x97, 0xc3, 0xee, 0x3f, 0x91, 0xaa, 0x89, 0x29,
	0x75, 0xef, 0x7f, 0xee, 0x40, 0x7b, 0x60, 0x12, 0xef, 0x1b, 0x83, 0x07, 0x4d, 0x22, 0x78, 0x28,
	0x2e, 0xcd, 0x7f, 0xc3, 0x74, 0x04, 0x2f, 0x36, 0x1e, 0x51, 0xaa, 0xf7, 0x7e, 0x30, 0x78, 0xd8,
	0x28, 0x5d, 0xfd, 0x35, 0x76, 0xd6, 0x66, 0x04, 0x2f, 0x37, 0x9f, 0x51, 0x09, 0xff, 0xc2, 0xe0,
	0xde, 0xff, 0xb2, 0xf2, 0xac, 0xf9, 0xae, 0x1a, 0x35, 0x38, 0x5c, 0x9b, 0x5a, 0xaa, 0xeb, 0x1f,
	0x9d, 0x2d, 0x39, 0x3b, 0x5f, 0x72, 0xf6, 0x7b, 0xc9, 0xd9, 0xa7, 0x15, 0x6f, 0x9d, 0xaf, 0x78,
	0xeb, 0xe7, 0x8a, 0xb7, 0xde, 0x3c, 0x49, 0xa6, 0xf6, 0xed, 0x62, 0x2c, 0x62, 0x4a, 0x23, 0x67,
	0x69, 0x94, 0xad, 0x89, 0x8a, 0x57, 0xf2, 0xa4, 0x2c, 0xec, 0xe9, 0x1c, 0xcd, 0x78, 0x3b, 0x7f,
	0xe1, 0x0e, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x57, 0x00, 0x73, 0x45, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	TransferFromTwitterToWalletByMerces(ctx context.Context, in *MsgTransferFromTwitterToWalletByMerces, opts ...grpc.CallOption) (*MsgTransferFromTwitterToWalletByMercesResponse, error)
	TransferFromTwitterToTwitterByMerces(ctx context.Context, in *MsgTransferFromTwitterToTwitterByMerces, opts ...grpc.CallOption) (*MsgTransferFromTwitterToTwitterByMercesResponse, error)
	TransferFromWalletToTwitter(ctx context.Context, in *MsgTransferFromWalletToTwitter, opts ...grpc.CallOption) (*MsgTransferFromWalletToTwitterResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) TransferFromTwitterToWalletByMerces(ctx context.Context, in *MsgTransferFromTwitterToWalletByMerces, opts ...grpc.CallOption) (*MsgTransferFromTwitterToWalletByMercesResponse, error) {
	out := new(MsgTransferFromTwitterToWalletByMercesResponse)
	err := c.cc.Invoke(ctx, "/mercestoken.planet.planet.Msg/TransferFromTwitterToWalletByMerces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferFromTwitterToTwitterByMerces(ctx context.Context, in *MsgTransferFromTwitterToTwitterByMerces, opts ...grpc.CallOption) (*MsgTransferFromTwitterToTwitterByMercesResponse, error) {
	out := new(MsgTransferFromTwitterToTwitterByMercesResponse)
	err := c.cc.Invoke(ctx, "/mercestoken.planet.planet.Msg/TransferFromTwitterToTwitterByMerces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferFromWalletToTwitter(ctx context.Context, in *MsgTransferFromWalletToTwitter, opts ...grpc.CallOption) (*MsgTransferFromWalletToTwitterResponse, error) {
	out := new(MsgTransferFromWalletToTwitterResponse)
	err := c.cc.Invoke(ctx, "/mercestoken.planet.planet.Msg/TransferFromWalletToTwitter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	TransferFromTwitterToWalletByMerces(context.Context, *MsgTransferFromTwitterToWalletByMerces) (*MsgTransferFromTwitterToWalletByMercesResponse, error)
	TransferFromTwitterToTwitterByMerces(context.Context, *MsgTransferFromTwitterToTwitterByMerces) (*MsgTransferFromTwitterToTwitterByMercesResponse, error)
	TransferFromWalletToTwitter(context.Context, *MsgTransferFromWalletToTwitter) (*MsgTransferFromWalletToTwitterResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) TransferFromTwitterToWalletByMerces(ctx context.Context, req *MsgTransferFromTwitterToWalletByMerces) (*MsgTransferFromTwitterToWalletByMercesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferFromTwitterToWalletByMerces not implemented")
}
func (*UnimplementedMsgServer) TransferFromTwitterToTwitterByMerces(ctx context.Context, req *MsgTransferFromTwitterToTwitterByMerces) (*MsgTransferFromTwitterToTwitterByMercesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferFromTwitterToTwitterByMerces not implemented")
}
func (*UnimplementedMsgServer) TransferFromWalletToTwitter(ctx context.Context, req *MsgTransferFromWalletToTwitter) (*MsgTransferFromWalletToTwitterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferFromWalletToTwitter not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_TransferFromTwitterToWalletByMerces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferFromTwitterToWalletByMerces)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferFromTwitterToWalletByMerces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mercestoken.planet.planet.Msg/TransferFromTwitterToWalletByMerces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferFromTwitterToWalletByMerces(ctx, req.(*MsgTransferFromTwitterToWalletByMerces))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferFromTwitterToTwitterByMerces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferFromTwitterToTwitterByMerces)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferFromTwitterToTwitterByMerces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mercestoken.planet.planet.Msg/TransferFromTwitterToTwitterByMerces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferFromTwitterToTwitterByMerces(ctx, req.(*MsgTransferFromTwitterToTwitterByMerces))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferFromWalletToTwitter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferFromWalletToTwitter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferFromWalletToTwitter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mercestoken.planet.planet.Msg/TransferFromWalletToTwitter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferFromWalletToTwitter(ctx, req.(*MsgTransferFromWalletToTwitter))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mercestoken.planet.planet.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferFromTwitterToWalletByMerces",
			Handler:    _Msg_TransferFromTwitterToWalletByMerces_Handler,
		},
		{
			MethodName: "TransferFromTwitterToTwitterByMerces",
			Handler:    _Msg_TransferFromTwitterToTwitterByMerces_Handler,
		},
		{
			MethodName: "TransferFromWalletToTwitter",
			Handler:    _Msg_TransferFromWalletToTwitter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "planet/tx.proto",
}

func (m *MsgTransferFromTwitterToWalletByMerces) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferFromTwitterToWalletByMerces) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferFromTwitterToWalletByMerces) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTransferFromTwitterToWalletByMercesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferFromTwitterToWalletByMercesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferFromTwitterToWalletByMercesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgTransferFromTwitterToTwitterByMerces) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferFromTwitterToTwitterByMerces) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferFromTwitterToTwitterByMerces) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ToUsername) > 0 {
		i -= len(m.ToUsername)
		copy(dAtA[i:], m.ToUsername)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ToUsername)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FromUsername) > 0 {
		i -= len(m.FromUsername)
		copy(dAtA[i:], m.FromUsername)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromUsername)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTransferFromTwitterToTwitterByMercesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferFromTwitterToTwitterByMercesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferFromTwitterToTwitterByMercesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgTransferFromWalletToTwitter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferFromWalletToTwitter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferFromWalletToTwitter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTransferFromWalletToTwitterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferFromWalletToTwitterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferFromWalletToTwitterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgTransferFromTwitterToWalletByMerces) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTx(uint64(m.Amount))
	}
	return n
}

func (m *MsgTransferFromTwitterToWalletByMercesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgTransferFromTwitterToTwitterByMerces) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.FromUsername)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ToUsername)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTx(uint64(m.Amount))
	}
	return n
}

func (m *MsgTransferFromTwitterToTwitterByMercesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgTransferFromWalletToTwitter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Coin.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgTransferFromWalletToTwitterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgTransferFromTwitterToWalletByMerces) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferFromTwitterToWalletByMerces: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferFromTwitterToWalletByMerces: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferFromTwitterToWalletByMercesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferFromTwitterToWalletByMercesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferFromTwitterToWalletByMercesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferFromTwitterToTwitterByMerces) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferFromTwitterToTwitterByMerces: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferFromTwitterToTwitterByMerces: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromUsername", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromUsername = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToUsername", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToUsername = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferFromTwitterToTwitterByMercesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferFromTwitterToTwitterByMercesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferFromTwitterToTwitterByMercesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferFromWalletToTwitter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferFromWalletToTwitter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferFromWalletToTwitter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferFromWalletToTwitterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferFromWalletToTwitterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferFromWalletToTwitterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
